home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('prod-details/<int:pk>', views.prod_details, name='productDetails'),

]

yfnstores/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    #path("ckeditor5/", include('django_ckeditor_5.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Products(models.Model):
    title = models.CharField(max_length=100)
    short_description = models.CharField(max_length=100, default="Please Click the Title for Detailed Description.")
    description =  RichTextField()
    image1 = models.ImageField(upload_to='post_images/', default='post_images/default.jpg',blank=True, null=True)
    image2 = models.ImageField(upload_to='post_images/', default='post_images/default.jpg',blank=True, null=True)
    image3 = models.ImageField(upload_to='post_images/', default='post_images/default.jpg',blank=True, null=True)
    cardLink = models.URLField(max_length=500)
    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render
from .models import Products
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives

def index(request):
    prod = Products.objects.all()
    context = {'Products':prod}
    if request.method == "POST":
        custName = request.POST.get("name")
        custEmail = request.POST.get("email")
        custsubject = "Inquirey About " + request.POST.get("subject")
        custBody = request.POST.get("message")
        subject = custsubject
        email_body = "Email From Name : "+ custName + " Email Address : " + custEmail + " Inquiry About : "+ custBody
        
        from_email = settings.EMAIL_HOST_USER
        to_email = ("yfnstores@gmail.com", "")
        Emailmessage = EmailMultiAlternatives(
            subject=subject, body=email_body, from_email=from_email, to=to_email
        )
        Emailmessage.content_subtype = "html"
        Emailmessage.send()
        messages.success(request, "Message sent." )
    return render(request, 'home/index.html', context)

def prod_details(request,pk):
    prod = Products.objects.get(id = pk)
    return render(request, 'home/product-details.html',{'prod_detail':prod})

home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio sections-bg">
  <div class="container" data-aos="fade-up">



    <div class="portfolio-isotope" data-portfolio-filter="*" data-portfolio-layout="masonry"
      data-portfolio-sort="original-order" data-aos="fade-up" data-aos-delay="100">

      <div>
        <ul class="portfolio-flters">

          <li data-filter=".filter-product">Product</li>

        </ul><!-- End Portfolio Filters -->
      </div>

      <div class="row gy-4 portfolio-container">
        {% for item in Products %}

        <div class="col-xl-4 col-md-6 portfolio-item filter-app">
          <div class="portfolio-wrap">
            <a href="{{item.image1.url}}" data-gallery="portfolio-gallery-app" class="glightbox"><img
                src="{{item.image1.url}}" class="img-fluid" alt=""></a>
            <div class="portfolio-info">
              <h4><a href="{% url 'home:productDetails' item.id %}" title="More Details">{{item.title}}</a></h4>
              {% comment %} <p>{{item.description|safe|slice:":100"}}</p> {% endcomment %}
              <p>{{item.short_description}}</p>
            </div>
          </div>
        </div><!-- End Portfolio Item -->
        {% endfor %}


      </div><!-- End Portfolio Container -->

    </div>

  </div>
</section><!-- End Portfolio Section -->



<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">

    <div class="section-header">
      <h2>Contact</h2>
      <p>Feel free to contact us anytime we will try to get back to you ASAP.</p>
    </div>
    {% for message in messages %}
    <div id="message_container" class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        
        {{ message }}
      </div>
    </div>
    {% endfor %}
    <div class="row gx-lg-0 gy-4">

      <div class="col-lg-4">

        <div class="info-container d-flex flex-column align-items-center justify-content-center">


          <div class="info-item d-flex">
            <i class="bi bi-envelope flex-shrink-0"></i>
            <div>
              <h4>Email:</h4>
              <p>yfnstores@gmail.com</p>
            </div>
          </div><!-- End Info Item -->



          <div class="info-item d-flex">
            <i class="bi bi-clock flex-shrink-0"></i>
            <div>
              <h4>Open Hours:</h4>
              <p>24 Hrs</p>
            </div>
          </div><!-- End Info Item -->
        </div>

      </div>

      <div class="col-lg-8">
        <form method="post" class="php-email-form">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-6 form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
            </div>
            <div class="col-md-6 form-group mt-3 mt-md-0">
              <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
            </div>
          </div>
          <div class="form-group mt-3">
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
          </div>
          <div class="form-group mt-3">
            <textarea class="form-control" name="message" rows="7" placeholder="Message" required></textarea>
          </div>
          <div class="my-3">
            <div class="loading">Loading</div>
            <div class="error-message"></div>
            <div class="sent-message">Your message has been sent. Thank you!</div>
          </div>
          <div class="text-center"><button type="submit" name="ESend">Send Message</button></div>
        </form>
      </div><!-- End Contact Form -->
      

    </div>

  </div>
</section><!-- End Contact Section -->

{% endblock content %}

home/templates/home/product-details.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- ======= Portfolio Details Section ======= -->
<section id="portfolio-details" class="portfolio-details">
    <div class="container" data-aos="fade-up">

        <div class="position-relative h-100" style="width: 70%; margin: auto;" >
            <div class="slides-1 portfolio-details-slider swiper">
                <div class="swiper-wrapper align-items-center">

                    <div class="swiper-slide">
                        <img src="{{prod_detail.image1.url}}" alt="">
                    </div>

                    <div class="swiper-slide">
                        <img src="{{prod_detail.image2.url}}" alt="">
                    </div>

                    <div class="swiper-slide">
                        <img src="{{prod_detail.image3.url}}" alt="">
                    </div>


                </div>
                <div class="swiper-pagination">
                    
                </div>
            </div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>

        </div>

        <div class="row justify-content-between gy-4 mt-4" style="width: 70%; margin: auto;">

            <div class="col-lg-8">
                <div class="portfolio-description">
                    <h2>{{prod_detail.title}}</h2>
                    <p>
                        {{prod_detail.description|safe}}
                    </p>


                </div>
            </div>

            <div class="col-lg-3">
                <div class="portfolio-info">
                    <h3>Item Link</h3>
                    <ul>

                        <li><iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="{{prod_detail.cardLink}}"></iframe></li>
                    </ul>
                </div>
            </div>

        </div>

    </div>
</section><!-- End Portfolio Details Section -->
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>YFN Stores - Home</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static "assets/img/favicon.png" %}" rel="icon">
  <link href="{% static "assets/img/apple-touch-icon.png" %}"rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static "assets/vendor/bootstrap/css/bootstrap.min.css" %}"rel="stylesheet">
  <link href="{% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %}"rel="stylesheet">
  <link href="{% static "assets/vendor/aos/aos.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/glightbox/css/glightbox.min.css" %}" rel="stylesheet">
  <link href="{% static "assets/vendor/swiper/swiper-bundle.min.css" %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static "assets/css/main.css" %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: YFN Stores - v1.1.1
  * Template URL: https://bootstrapmade.com/YFN Stores-bootstrap-business-website-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <section id="topbar" class="topbar d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:yfnstores@gmail.com">yfnstores@gmail.com</a></i>
        
      </div>
      <div class="social-links d-none d-md-flex align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section><!-- End Top Bar -->

  <header id="header" class="header d-flex align-items-center">

    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="{% url 'home:index' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="{% static "assets/img/logo.png" alt=""> -->
        <h1>YFN Stores<span>.</span></h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="#hero">Home</a></li>
          
          <li><a href="#portfolio">Products</a></li>
          
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav><!-- .navbar -->

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="hero">
    <div class="container position-relative">
      <div class="row gy-5" data-aos="fade-in">
        <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center text-center text-lg-start">
          <h2>Welcome</h2>
          <p>Every product is independently selected by (obsessive) editors. Things you buy through our links may earn us a commission.</p>
          
        </div>
        <div class="col-lg-6 order-1 order-lg-2">
          <img src="{% static "assets/img/hero-img.svg" %}" class="img-fluid" alt="" data-aos="zoom-out" data-aos-delay="100">
        </div>
      </div>
    </div>

    

    </div>
  </section>
  <!-- End Hero Section -->

  <main id="main">

    {% block content %}
    
    {% endblock content %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="{% url 'home:index' %}" class="logo d-flex align-items-center">
            <span>YFN Stores</span>
          </a>
          <p>We believe a single blog  can change people's decisions...is that crazy?</p>
          <div class="social-links d-flex mt-4">
            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          
        </div>

        <div class="col-lg-2 col-6 footer-links">
          
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            <strong>Email:</strong> yfnstores@gmail.com<br>
          </p>

        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
        &copy; Copyright <strong><span>YFN Stores</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/YFN Stores-bootstrap-business-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "assets/vendor/aos/aos.js" %}"></script>
  <script src="{% static "assets/vendor/glightbox/js/glightbox.min.js" %}"></script>
  <script src="{% static "assets/vendor/purecounter/purecounter_vanilla.js" %}"></script>
  <script src="{% static "assets/vendor/swiper/swiper-bundle.min.js" %}"></script>
  <script src="{% static "assets/vendor/isotope-layout/isotope.pkgd.min.js" %}"></script>
  <script src="{% static "assets/vendor/php-email-form/validate.js" %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static "assets/js/main.js" %}"></script>
<script>
  // suppose the `id` attribute of element is `message_container`.
var message_ele = document.getElementById("message_container");

setTimeout(function(){ 
   message_ele.style.display = "none"; 
}, 5000);
// Timeout is 3 sec, you can change it
</script>
</body>

</html>